### ISSUE TITLE
Sponsor User Program

### ISSUE THREAD

**Issue by air2h2o** [IBM-Design/idr-alpha#43]
Scott, this should be a light lift from a content perspective. Porting http://idr-prod.w3ibm.mybluemix.net/design/research/resources/sponsor-user-program/ (with a few copy edits) to our external site.

**Comment by sstrubberg** [comment]
I need wires.

**Comment by sstrubberg** [comment]
@CrisGonzo  ???

**Comment by sstrubberg** [comment]
Issue moved to [IBM-Design/idr #10](https://github.com/IBM-Design/idr/issues/10) via [**ZenHub**](https://www.zenhub.com/)
