### ISSUE TITLE
Landing page: Feature cards— Adjust gradient and type size

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/idr-alpha#51]
The magenta should have a touch oaf black in it as it transitions to magenta. See Watson site "About" page

https://www.ibm.com/watson/about

Also check type size I think it needs to be a touch smaller (also see #47 for line spacing issue)

current (no gradient)

![Screen Shot 2019-06-13 at 3 27 10 PM](https://user-images.githubusercontent.com/32881239/59461771-25f52100-8df0-11e9-8b02-48a9b5d38d22.png)

expected (with gradient but with magenta)

![Screen Shot 2019-06-13 at 3 27 03 PM](https://user-images.githubusercontent.com/32881239/59461807-39a08780-8df0-11e9-852f-59aa9fff4227.png)

**Comment by sstrubberg** [comment]
Issue moved to [IBM-Design/idr #9](https://github.com/IBM-Design/idr/issues/9) via [**ZenHub**](https://www.zenhub.com/)
